import { EExecutionLocation } from '../execution/location'
import { EFFORT_LADDER, EEffort } from '../models/effort-ladder'
import { EClassifierMode } from '../policy/classifier/triage'
import { EWebSearchBackend } from '../web/search'
import { ESettingPage, type SettingDefinition, type SettingPage } from './definition'
import { ESettingKind, type SettingOption } from './value'

export const SETTING_PAGES: readonly SettingPage[] = [
  { id: ESettingPage.General, label: 'general' },
  { id: ESettingPage.Models, label: 'models' },
  { id: ESettingPage.Appearance, label: 'appearance' },
  { id: ESettingPage.Account, label: 'account' },
]

export enum ESettingId {
  SmoothStreaming = 'transcript.smoothStreaming',
  ThinkingBlocks = 'transcript.thinkingBlocks',
  SidebarWidth = 'sidebar.width',
  SidebarFoldBelow = 'sidebar.foldBelow',
  ProjectInstructions = 'context.projectInstructions',
  UserInstructions = 'context.userInstructions',
  InstructionFilenames = 'context.filenames',
  ReloadInstructions = 'context.reload',
  AutoCompact = 'context.autoCompact',
  ImageRows = 'transcript.imageRows',
  FenceWrap = 'transcript.fenceWrap',
  TldrFooter = 'tldr.footer',
  TldrStatus = 'tldr.status',
  WorktreeDirectory = 'worktree.directory',
  FooterMeters = 'usage.meters',
  WarnFiveHour = 'usage.warnFiveHour',
  WarnWeekly = 'usage.warnWeekly',
  Accent = 'appearance.accent',
  BlockPadding = 'appearance.blockPadding',
  ComposerEdge = 'appearance.composerEdge',
  ClassifierMode = 'classifier.mode',
  NoticeSeconds = 'notifications.seconds',
  WebSearchBackend = 'web.searchBackend',
  WebSearchKey = 'web.searchKey',
  ModelId = 'model.id',
  ModelEffort = 'model.effort',
  QuickModel = 'model.quickModel',
  CompactionModel = 'model.compactionModel',
  ModelFavourites = 'model.favourites',
  SubagentModel = 'agents.subagentModel',
  ExecutionLocation = 'execution.location',
  ContainerCpus = 'container.cpus',
  ContainerMemory = 'container.memory',
  ContainerIdleMinutes = 'container.idleMinutes',
  DatabaseUrl = 'store.databaseUrl',
  KeychainService = 'credentials.keychainService',
  CloudUrl = 'cloud.url',
  CloudRequired = 'cloud.required',
  AutoRestart = 'dev.autoRestart',
}

export const DEFAULT_WORKTREE_DIRECTORY = '.atlas/worktrees'

export const DEFAULT_CONTAINER_IDLE_MINUTES = 30

export const DEFAULT_EFFORT = EEffort.Medium

const EFFORT_OPTIONS: readonly SettingOption[] = EFFORT_LADDER.map((effort) => ({
  value: effort,
  label: effort,
}))

export const ATLAS_SETTINGS: readonly SettingDefinition[] = [
  {
    id: ESettingId.SmoothStreaming,
    page: ESettingPage.General,
    group: 'Transcript',
    label: 'Smooth streaming',
    description:
      'Reveal assistant text at reading pace instead of the rate the model emits it. Turning this off shows every chunk the moment it lands.',
    environmentVariable: 'ATLAS_SMOOTH_STREAMING',
    kind: ESettingKind.Toggle,
    fallback: true,
  },
  {
    id: ESettingId.ThinkingBlocks,
    page: ESettingPage.General,
    group: 'Transcript',
    label: 'Thinking blocks',
    description:
      'What the transcript keeps of the reasoning behind an answer. Keep leaves a summary row behind that unfolds into the whole thought; while streaming shows the live tail and holds it until something lands under it — the answer, or the end of the turn; hide never renders reasoning at all. Adjacent thoughts always fold into one block.',
    environmentVariable: 'ATLAS_THINKING_BLOCKS',
    kind: ESettingKind.Choice,
    fallback: 'keep',
    options: [
      { value: 'keep', label: 'keep', detail: 'shipped' },
      { value: 'stream', label: 'while streaming' },
      { value: 'hidden', label: 'hide' },
    ],
  },
  {
    id: ESettingId.ImageRows,
    page: ESettingPage.General,
    group: 'Transcript',
    label: 'Tallest image',
    description:
      'How many rows a picture in the transcript may fill. In a terminal that draws real pixels this is the resolution knob, not just the size one — the image is transmitted at the pixel size of the cell box it is given, so a taller box is a sharper picture. Tall images push the text around them further apart, which is the trade.',
    environmentVariable: 'ATLAS_IMAGE_ROWS',
    kind: ESettingKind.Range,
    fallback: 30,
    minimum: 8,
    maximum: 80,
    step: 2,
    unit: ' rows',
  },
  {
    id: ESettingId.FenceWrap,
    page: ESettingPage.General,
    group: 'Transcript',
    label: 'Soft-wrap fences',
    description:
      'What a fenced block does with a line that runs past the panel. Never gives every fence a sideways pan on alt+wheel, keeping each line whole. Text wraps the fences that hold prose — markdown, plain text and shell commands, the shape a quoted answer or a long one-liner takes — and leaves code alone, because a wrapped line of code reads as two lines that were never written. All wraps every fence, code included.',
    environmentVariable: 'ATLAS_FENCE_WRAP',
    kind: ESettingKind.Choice,
    fallback: 'text',
    options: [
      { value: 'text', label: 'text', detail: 'shipped' },
      { value: 'never', label: 'never', detail: 'pan instead' },
      { value: 'all', label: 'all', detail: 'code too' },
    ],
  },
  {
    id: ESettingId.TldrFooter,
    page: ESettingPage.General,
    group: 'Transcript',
    label: 'tl;dr footer',
    description:
      'When a turn ends, a second, cheaper model writes a one-to-two-line summary of it — from your last message to the end — and the transcript shows it as a tl;dr divider under the answer. The summary is for you alone: the agent never reads it. Turning this off stops new footers being written; ones already on the log stay.',
    environmentVariable: 'ATLAS_TLDR_FOOTER',
    kind: ESettingKind.Toggle,
    fallback: true,
  },
  {
    id: ESettingId.TldrStatus,
    page: ESettingPage.General,
    group: 'Transcript',
    label: 'tl;dr status pill',
    description:
      'The filled pill centred on the tl;dr divider saying how the turn ended — done, needs you, or waiting. Display only: the status is still written with every footer, so turning this back on shows it on footers that were written while it was off.',
    environmentVariable: 'ATLAS_TLDR_STATUS',
    kind: ESettingKind.Toggle,
    fallback: true,
  },
  {
    id: ESettingId.SidebarWidth,
    page: ESettingPage.General,
    group: 'Layout',
    label: 'Sidebar width',
    description:
      'How many columns every side pane takes: the transcript sidebar, the model picker, and the explanation beside these settings.',
    environmentVariable: 'ATLAS_SIDEBAR_WIDTH',
    kind: ESettingKind.Range,
    fallback: 42,
    minimum: 30,
    maximum: 64,
    step: 2,
    unit: ' cols',
  },
  {
    id: ESettingId.SidebarFoldBelow,
    page: ESettingPage.General,
    group: 'Layout',
    label: 'Fold the sidebar below',
    description:
      'The terminal width at which the sidebar stops docking beside the transcript and becomes an overlay you open with ctrl+b and close with escape. Above it the sidebar is always docked. Set it to match the narrowest tile you want the sidebar in. A width that leaves the transcript no room folds regardless of this.',
    environmentVariable: 'ATLAS_SIDEBAR_FOLD_BELOW',
    kind: ESettingKind.Range,
    fallback: 120,
    minimum: 60,
    maximum: 240,
    step: 2,
    unit: ' cols',
  },
  {
    id: ESettingId.ProjectInstructions,
    page: ESettingPage.General,
    group: 'Project context',
    label: 'Project instructions',
    description:
      'Load the instruction files a repository carries for its agents, walking the workspace root down to the working directory so that a deeper file overrides a shallower one.',
    environmentVariable: 'ATLAS_PROJECT_INSTRUCTIONS',
    kind: ESettingKind.Toggle,
    fallback: true,
  },
  {
    id: ESettingId.UserInstructions,
    page: ESettingPage.General,
    group: 'Project context',
    label: 'Personal instructions',
    description:
      'Also load ATLAS.md from your Atlas home directory, which applies to every project. It is read before the repository, so anything the repository says wins.',
    environmentVariable: 'ATLAS_USER_INSTRUCTIONS',
    kind: ESettingKind.Toggle,
    fallback: true,
  },
  {
    id: ESettingId.InstructionFilenames,
    page: ESettingPage.General,
    group: 'Project context',
    label: 'Borrowed instruction files',
    description:
      'Which instruction files borrowed from another harness a repository is read for. ATLAS.md is always read and is loaded last, so it wins a disagreement with either borrowed file; AGENTS.md is the cross-vendor convention and CLAUDE.md the Claude-specific one, and when both are read CLAUDE.md is loaded second. A .local.md sibling of any of the three is read after all of them and is never checked in.',
    environmentVariable: 'ATLAS_INSTRUCTION_FILENAMES',
    kind: ESettingKind.Choice,
    fallback: 'both',
    options: [
      { value: 'both', label: 'AGENTS.md + CLAUDE.md', detail: 'shipped' },
      { value: 'claude', label: 'CLAUDE.md' },
      { value: 'agents', label: 'AGENTS.md' },
      { value: 'none', label: 'neither', detail: 'ATLAS.md only' },
    ],
  },
  {
    id: ESettingId.ReloadInstructions,
    page: ESettingPage.General,
    group: 'Project context',
    label: 'Reload on change',
    description:
      'Re-read the instruction files at every turn, so editing one takes effect in the conversation you are already in. Unchanged files cost nothing; a changed one is appended again and supersedes what the model was reading. Turning this off freezes the instructions as they were when the conversation opened.',
    environmentVariable: 'ATLAS_RELOAD_INSTRUCTIONS',
    kind: ESettingKind.Toggle,
    fallback: true,
  },
  {
    id: ESettingId.AutoCompact,
    page: ESettingPage.General,
    group: 'Context window',
    label: 'Compact automatically at',
    description:
      'How full the context window may get before Atlas summarises the older turns without being asked. It checks when a turn ends, so a turn is never interrupted to do it, and it compacts mid-turn only when a step would otherwise overflow the window outright. Set to zero to compact only when you ask with /compact.',
    environmentVariable: 'ATLAS_AUTO_COMPACT',
    kind: ESettingKind.Range,
    fallback: 90,
    minimum: 0,
    maximum: 100,
    step: 5,
    unit: '%',
  },
  {
    id: ESettingId.WorktreeDirectory,
    page: ESettingPage.General,
    group: 'Worktrees',
    label: 'Where worktrees go',
    description:
      'The directory, relative to the repository root, that enter_worktree creates a worktree in. Atlas writes a .gitignore of its own inside it, so the checkouts never show up as untracked files however the repository is configured.',
    environmentVariable: 'ATLAS_WORKTREE_DIRECTORY',
    kind: ESettingKind.Choice,
    fallback: DEFAULT_WORKTREE_DIRECTORY,
    options: [
      { value: DEFAULT_WORKTREE_DIRECTORY, label: DEFAULT_WORKTREE_DIRECTORY, detail: 'shipped' },
      { value: '.worktrees', label: '.worktrees' },
    ],
  },
  {
    id: ESettingId.FooterMeters,
    page: ESettingPage.General,
    group: 'Usage meters',
    label: 'Meters in the footer',
    description:
      'Which meters the footer carries. The context meter reports the window the current conversation occupies; the session and weekly meters report how much of the account\'s own rate limits have been spent, read from Anthropic rather than counted here. Narrowing this does not stop Atlas reading them, it stops the footer spelling them out.',
    environmentVariable: 'ATLAS_FOOTER_METERS',
    kind: ESettingKind.Choice,
    fallback: 'all',
    options: [
      { value: 'all', label: 'all', detail: 'ctx · 5h · wk' },
      { value: 'session', label: 'session', detail: 'ctx · 5h' },
      { value: 'context', label: 'context only', detail: 'ctx' },
    ],
  },
  {
    id: ESettingId.WarnFiveHour,
    page: ESettingPage.General,
    group: 'Usage meters',
    label: 'Warn on the session window at',
    description:
      'How much of the five-hour window may be spent before the footer stops being ambient and starts colouring the figure. The two bands above this one are spaced across whatever headroom is left, so moving this moves all of them.',
    environmentVariable: 'ATLAS_WARN_FIVE_HOUR',
    kind: ESettingKind.Range,
    fallback: 65,
    minimum: 0,
    maximum: 100,
    step: 5,
    unit: '%',
  },
  {
    id: ESettingId.WarnWeekly,
    page: ESettingPage.General,
    group: 'Usage meters',
    label: 'Warn on the weekly window at',
    description:
      'The same threshold for the seven-day window. It earns attention later than the session window by default, because a two-thirds-spent week is simply Thursday, where a two-thirds-spent five hours is the one that walls you mid-task.',
    environmentVariable: 'ATLAS_WARN_WEEKLY',
    kind: ESettingKind.Range,
    fallback: 70,
    minimum: 0,
    maximum: 100,
    step: 5,
    unit: '%',
  },
  {
    id: ESettingId.ClassifierMode,
    page: ESettingPage.General,
    group: 'Nudges',
    label: 'Nudge before damage',
    description:
      'Whether a second, cheaper model looks at a call that trips one of the deterministic probes — an irreversible removal, a reach outside the project, a write into a worktree another agent is holding — and decides whether interrupting you is warranted. Shadow watches and records without ever pausing anything, which is how the pause rate gets measured before it is trusted; nudge lets it ask.',
    environmentVariable: 'ATLAS_CLASSIFIER_MODE',
    kind: ESettingKind.Choice,
    fallback: EClassifierMode.Shadow,
    options: [
      {
        value: EClassifierMode.Off,
        label: 'off',
        detail: 'no classification',
        note: 'Nothing is derived and nothing is recorded. The call goes to the tool exactly as it would have without this feature.',
      },
      {
        value: EClassifierMode.Shadow,
        label: 'shadow',
        detail: 'watches only',
        note: 'The whole pipeline runs and writes a row saying what it would have done, and every call still runs. This is where the rate of would-be interruptions becomes a number rather than a fear.',
      },
      {
        value: EClassifierMode.Nudge,
        label: 'nudge',
        detail: 'may ask',
        note: 'The same pipeline, except that a call the judge says it cannot let pass unseen stops and asks you. Only a model that can name what would be lost is allowed to interrupt.',
      },
    ],
  },
  {
    id: ESettingId.NoticeSeconds,
    page: ESettingPage.General,
    group: 'Notifications',
    label: 'Toast duration',
    description:
      'How long a notification floats above the composer before it fades. Warnings from boot — a plugin that refused to load, an MCP server that did not come up — stay several times longer regardless, and anything that names a condition rather than an event, like the nudge classifier being unreachable, stands until the condition clears.',
    environmentVariable: 'ATLAS_NOTICE_SECONDS',
    kind: ESettingKind.Range,
    fallback: 2,
    minimum: 1,
    maximum: 10,
    step: 1,
    unit: ' s',
  },
  {
    id: ESettingId.AutoRestart,
    page: ESettingPage.General,
    group: 'Development',
    label: 'Restart atlas-dev when it goes stale',
    description:
      'Only an atlas-dev session can go stale — one running straight from the source tree, while the tree moves under it. When it does, the session exits at the end of the next turn and the wrapper rebuilds from source and relaunches, resuming the conversation where it was. The restart never fires while tasks are still running, a message is queued or half-typed, or an approval is waiting — then the stale notice stands instead, and the restart waits for a clean moment. Off means the notice is all you ever get.',
    environmentVariable: 'ATLAS_AUTO_RESTART',
    kind: ESettingKind.Toggle,
    fallback: true,
  },
  {
    id: ESettingId.WebSearchBackend,
    page: ESettingPage.General,
    group: 'Web',
    label: 'Search backend',
    description:
      'Which search service web_search asks. Every one of them is somebody else\u2019s, so Atlas picks none for you: DuckDuckGo works with no account at all and is the fallback, and the rest are better in exchange for a key you get yourself. The ones that return the text of each page rather than a one-line snippet are worth the setup, because a result carrying its own text saves the model a fetch per link.',
    environmentVariable: 'ATLAS_SEARCH_BACKEND',
    kind: ESettingKind.Choice,
    fallback: EWebSearchBackend.DuckDuckGo,
    options: [
      {
        value: EWebSearchBackend.DuckDuckGo,
        label: 'DuckDuckGo',
        detail: 'no key',
        note: 'Nothing to set up, and nothing to sign up for. Returns a title and a snippet per result, so reading anything means a web_fetch after it, and it throttles unauthenticated searches \u2014 a busy session will meet a rate limit and have to wait.',
      },
      {
        value: EWebSearchBackend.Jina,
        label: 'Jina',
        detail: 'key optional',
        note: 'Returns the extracted text of each page, not just a snippet. Works anonymously at 20 searches a minute, which a single session rarely exceeds; a free key raises that to 500.',
      },
      {
        value: EWebSearchBackend.Tavily,
        label: 'Tavily',
        detail: 'key needed',
        note: 'Built for agents rather than for people: results come back with the full page text already extracted. A thousand searches a month are free and no card is asked for.',
      },
      {
        value: EWebSearchBackend.Exa,
        label: 'Exa',
        detail: 'key needed',
        note: 'Embedding-based search that reads queries written as sentences rather than as keywords, and returns page text with each result. Generous free tier, no card.',
      },
      {
        value: EWebSearchBackend.Brave,
        label: 'Brave',
        detail: 'key needed',
        note: 'An index of its own rather than a wrapper over somebody else\u2019s, with clean, fast results. Snippets only, so reading still costs a fetch, and every plan now wants a card on file \u2014 including the free credits.',
      },
      {
        value: EWebSearchBackend.SearXNG,
        label: 'SearXNG',
        detail: 'instance url',
        note: 'Your own metasearch instance, so the queries leave no account behind. Set the row below to its address. Public instances almost always disable the JSON output this needs, so in practice this means one you run.',
      },
    ],
  },
  {
    id: ESettingId.WebSearchKey,
    page: ESettingPage.General,
    group: 'Web',
    label: 'Search key',
    description:
      'What the selected backend needs before it will answer \u2014 a key for most of them, an address for a SearXNG instance of your own. It belongs to whichever backend is chosen above, so switching backend shows the one that backend needs. Atlas never reads it from the environment and never writes it to a settings file: it is sealed in the secrets file beside the account vault, and only the last four characters are ever shown again.',
    kind: ESettingKind.Secret,
    fallback: '',
    masked: true,
  },
  {
    id: ESettingId.Accent,
    page: ESettingPage.Appearance,
    group: 'Colour',
    label: 'Accent',
    description:
      'The one hue that carries the harness through the whole app: block marks, the composer rail, the caret and inline code.',
    environmentVariable: 'ATLAS_ACCENT',
    kind: ESettingKind.Choice,
    fallback: 'clay',
    options: [
      { value: 'clay', label: 'clay', detail: 'shipped' },
      { value: 'slate', label: 'slate' },
      { value: 'moss', label: 'moss' },
      { value: 'plum', label: 'plum' },
    ],
  },
  {
    id: ESettingId.BlockPadding,
    page: ESettingPage.Appearance,
    group: 'Density',
    label: 'Block padding',
    description:
      'How much room a banded slab spends on its own chrome: code fences, diffs and failed turns. Comfort opens the band on a half row of its own and seams it off the body below; compact starts on the header row and runs straight into the content.',
    environmentVariable: 'ATLAS_BLOCK_PADDING',
    kind: ESettingKind.Choice,
    fallback: 'comfort',
    options: [
      { value: 'comfort', label: 'comfort', detail: 'shipped' },
      { value: 'compact', label: 'compact' },
    ],
  },
  {
    id: ESettingId.ComposerEdge,
    page: ESettingPage.Appearance,
    group: 'Composer',
    label: 'Composer edge',
    description:
      'How the draft separates itself from the transcript above it. Slab gives the composer a darker ground of its own and opens it on a half row, marked down the left by the accent rail. Bordered drops that second ground and draws a thin accent frame on all four sides instead, with the session title set into the top edge. Claude keeps those two rules and drops the sides, leading the draft with a prompt caret at the margin.',
    environmentVariable: 'ATLAS_COMPOSER_EDGE',
    kind: ESettingKind.Choice,
    fallback: 'slab',
    options: [
      { value: 'slab', label: 'slab', detail: 'shipped' },
      { value: 'bordered', label: 'bordered' },
      { value: 'claude', label: 'claude' },
    ],
  },
  {
    id: ESettingId.ModelId,
    page: ESettingPage.Models,
    group: 'Model',
    label: 'Default model',
    description:
      'The model a conversation starts on when it has not been given one of its own. Every conversation remembers the model it was last switched to, so this is only what a new one begins with — which is why the switcher no longer writes it and this row does. --model outranks it for one launch.',
    environmentVariable: 'ATLAS_MODEL',
    kind: ESettingKind.Model,
    fallback: '',
    unsetLabel: 'automatic',
  },
  {
    id: ESettingId.ModelEffort,
    page: ESettingPage.Models,
    group: 'Model',
    label: 'Default effort',
    description:
      'How much thinking a model that takes a budget is given before it answers, for a conversation that has not been given an effort of its own. Choosing a default model beside this sets both at once; a model that offers no budget ignores it.',
    environmentVariable: 'ATLAS_EFFORT',
    kind: ESettingKind.Choice,
    fallback: DEFAULT_EFFORT,
    options: EFFORT_OPTIONS,
  },
  {
    id: ESettingId.QuickModel,
    page: ESettingPage.Models,
    group: 'Background processes',
    label: 'Quick calls',
    description:
      'The model the quick background calls run on — tl;dr footers, session titles and the nudge judge — all of which pin a low effort and never read the conversation\u2019s own model. Left empty, they follow the default model. One choice serves them all: it is how you move the quick tier onto a cheaper model, or onto another provider when the usual one is having a bad day.',
    environmentVariable: 'ATLAS_QUICK_MODEL',
    kind: ESettingKind.Model,
    fallback: '',
    unsetLabel: 'follow default',
  },
  {
    id: ESettingId.CompactionModel,
    page: ESettingPage.Models,
    group: 'Background processes',
    label: 'Compaction',
    description:
      'The model that summarises older turns when the context window fills, both for the automatic compaction and for /compact. The summary is all the next turn sees of what it replaces, so a weak model here costs the conversation its memory. Left empty, it follows the default model.',
    environmentVariable: 'ATLAS_COMPACTION_MODEL',
    kind: ESettingKind.Model,
    fallback: '',
    unsetLabel: 'follow default',
  },
  {
    id: ESettingId.SubagentModel,
    page: ESettingPage.Models,
    group: 'Background processes',
    label: 'Sub-agents',
    description:
      'The model every sub-agent runs on unless its own type is given one below or pins one in its definition. Left empty, a sub-agent runs on whatever model the conversation that spawned it is on.',
    environmentVariable: 'ATLAS_SUBAGENT_MODEL',
    kind: ESettingKind.Model,
    fallback: '',
    unsetLabel: 'inherit conversation',
  },
  {
    id: ESettingId.ModelFavourites,
    page: ESettingPage.Hidden,
    group: 'Model',
    label: 'Pinned models',
    description:
      'The models the switcher gathers into its own group at the top of the list, in the order they were pinned. Written by the switcher rather than set here.',
    environmentVariable: 'ATLAS_MODEL_FAVOURITES',
    kind: ESettingKind.Text,
    fallback: '',
  },
  {
    id: ESettingId.ExecutionLocation,
    page: ESettingPage.General,
    group: 'Execution',
    label: 'Where sessions run',
    description:
      'Where a conversation that has not been given a location of its own executes its tools. Every conversation remembers the location it was last switched to, so this is only what a new one begins with — /container writes the conversation, and --execution-location outranks this row for one launch.',
    environmentVariable: 'ATLAS_EXECUTION_LOCATION',
    kind: ESettingKind.Choice,
    fallback: EExecutionLocation.Host,
    options: [
      { value: EExecutionLocation.Host, label: 'host', detail: 'shipped' },
      { value: EExecutionLocation.Docker, label: 'docker' },
    ],
  },
  {
    id: ESettingId.ContainerCpus,
    page: ESettingPage.General,
    group: 'Execution',
    label: 'Container CPUs',
    description:
      'How many cores each sandboxed conversation may use, as a ceiling the daemon enforces rather than a reservation. Every container gets this many, so a machine running several sandboxes at once can be oversubscribed — Atlas warns when the running total outruns the machine rather than pretending the limit is a guarantee.',
    environmentVariable: 'ATLAS_CONTAINER_CPUS',
    kind: ESettingKind.Range,
    fallback: 4,
    minimum: 1,
    maximum: 32,
    step: 1,
    unit: ' cpus',
  },
  {
    id: ESettingId.ContainerMemory,
    page: ESettingPage.General,
    group: 'Execution',
    label: 'Container memory',
    description:
      'How much memory each sandboxed conversation may use, in gigabytes, as a hard ceiling — a container that crosses it is killed by the daemon, which looks like a stack dying for no reason. Every container gets this much, and stopped containers keep their disk but hold no memory, so the number only competes with the sandboxes actually running.',
    environmentVariable: 'ATLAS_CONTAINER_MEMORY',
    kind: ESettingKind.Range,
    fallback: 8,
    minimum: 1,
    maximum: 128,
    step: 1,
    unit: ' GB',
  },
  {
    id: ESettingId.ContainerIdleMinutes,
    page: ESettingPage.General,
    group: 'Execution',
    label: 'Stop an idle container after',
    description:
      'How many minutes a sandboxed conversation may go without a bash call before Atlas stops its container. Stopping keeps the container\u2019s disk — the installed dependencies and build caches — so the next session brings it back in about a second, and a background shell that is still running always holds the stop off, so a dev server is never taken down by this.',
    environmentVariable: 'ATLAS_CONTAINER_IDLE_MINUTES',
    kind: ESettingKind.Range,
    fallback: DEFAULT_CONTAINER_IDLE_MINUTES,
    minimum: 5,
    maximum: 240,
    step: 5,
    unit: ' min',
  },
  {
    id: ESettingId.DatabaseUrl,
    page: ESettingPage.Hidden,
    group: 'Store',
    label: 'Database',
    description:
      'Where the event log and the threads over it are kept. Left empty, it is harness.db inside the Atlas home — which ATLAS_HOME moves, since a home has to be found before a settings file in it can be read.',
    environmentVariable: 'ATLAS_DATABASE_URL',
    kind: ESettingKind.Text,
    fallback: '',
  },
  {
    id: ESettingId.CloudUrl,
    page: ESettingPage.Hidden,
    group: 'Cloud',
    label: 'Cloud API',
    description:
      'Where the Atlas Cloud API lives — the backend that is the source of truth for accounts, secrets and the user MCP layer. The fallback is the production deployment; an Atlas contributor running apps/api next to the TUI points this at the local development server instead.',
    environmentVariable: 'ATLAS_CLOUD_URL',
    kind: ESettingKind.Text,
    fallback: 'https://api.byatlas.io',
  },
  {
    id: ESettingId.CloudRequired,
    page: ESettingPage.Hidden,
    group: 'Cloud',
    label: 'Cloud is the only store',
    description:
      'When on, Atlas Cloud is the only credential store and signing in is required — a signed-out Atlas refuses to read or write accounts, secrets, or the user MCP layer rather than touching the local vault. This is the shipped default. Turning it off is the escape hatch for developing the cloud API itself against a local apps/api, with the local vault active again.',
    environmentVariable: 'ATLAS_CLOUD_REQUIRED',
    kind: ESettingKind.Toggle,
    fallback: true,
  },
  {
    id: ESettingId.KeychainService,
    page: ESettingPage.Hidden,
    group: 'Credentials',
    label: 'Keychain item',
    description:
      'The keychain item a Claude Code login is imported from on boot, and written back to when Atlas refreshes it. Left empty, it is the item Claude Code itself writes.',
    environmentVariable: 'ATLAS_KEYCHAIN_SERVICE',
    kind: ESettingKind.Text,
    fallback: '',
  },
]
