#!/usr/bin/env bun
import { readdir } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

import { atlasDirectory } from '../src/store/paths'
import { PLUGIN_API_MODULES } from '../src/plugins/api'
import { ATLAS_PLUGIN_SPECIFIER } from '../src/plugins/install-api'

export const PLUGIN_TYPES_FILE_NAME = 'atlas.d.ts'

export const PLUGIN_TYPES_DIRECTORY_NAME = 'types'

const CORE_SPECIFIER = "'@dltech/atlas-core'"

const CORE_ENTRY = ['packages', 'core', 'src', 'index']

const DECLARATION_ENTRIES = [
  ['packages', 'core', 'src', 'index.ts'],
  ['packages', 'harness', 'src', 'plugins', 'plugin.ts'],
]

const HEADER = '// GENERATED by packages/harness/scripts/generate-plugin-types.ts — do not edit.'

// TS2439 forbids an import or export *declaration* inside an ambient module from naming a relative
// or rooted path, so the shipped file reaches the real declarations through import *types*, which
// carry no such restriction. https://github.com/microsoft/TypeScript/issues/14877
const valueLine = (args: { name: string; from: string }): string =>
  `  export const ${args.name}: typeof import('${args.from}').${args.name}`

const typeLine = (args: { name: string; from: string }): string =>
  `  export type ${args.name} = import('${args.from}').${args.name}`

const sorted = (names: readonly string[]): readonly string[] => [...names].sort()

export function renderPluginTypes(args: { declarationRoot: string }): string {
  const body = PLUGIN_API_MODULES.flatMap((module) => {
    const from = join(args.declarationRoot, ...module.path)
    return [
      ...sorted(module.values).map((name) => valueLine({ name, from })),
      ...sorted([...module.valueTypes, ...module.types]).map((name) => typeLine({ name, from })),
    ]
  })

  return [HEADER, '', `declare module '${ATLAS_PLUGIN_SPECIFIER}' {`, ...body, '}', ''].join('\n')
}

const declarationFilesIn = async (directory: string): Promise<readonly string[]> => {
  const entries = await readdir(directory, { withFileTypes: true, recursive: true })
  return entries
    .filter((entry) => entry.isFile() && entry.name.endsWith('.d.ts'))
    .map((entry) => join(entry.parentPath, entry.name))
}

// The emitted declarations import '@dltech/atlas-core' by name, and a plugin author's project has
// no such package. Pointing them at their own sibling declarations is what makes the shipped types
// resolve on their own; without it every core type silently degrades to any under skipLibCheck.
const resolveCoreImports = async (declarationRoot: string): Promise<void> => {
  const target = join(declarationRoot, ...CORE_ENTRY)

  for (const path of await declarationFilesIn(declarationRoot)) {
    const text = await Bun.file(path).text()
    if (!text.includes(CORE_SPECIFIER)) continue

    const toCore = relative(dirname(path), target)
    const specifier = toCore.startsWith('.') ? toCore : `./${toCore}`
    await Bun.write(path, text.replaceAll(CORE_SPECIFIER, `'${specifier}'`))
  }
}

export async function emitPluginDeclarations(args: {
  sourceRoot: string
  declarationRoot: string
}): Promise<void> {
  const emitted = Bun.spawn(
    [
      'bunx',
      'tsc',
      '--ignoreConfig',
      '--declaration',
      '--emitDeclarationOnly',
      '--outDir',
      args.declarationRoot,
      '--rootDir',
      args.sourceRoot,
      '--target',
      'ES2023',
      '--lib',
      'ES2023,DOM',
      '--module',
      'Preserve',
      '--moduleResolution',
      'bundler',
      '--strict',
      '--skipLibCheck',
      '--types',
      'bun',
      ...DECLARATION_ENTRIES.map((entry) => join(args.sourceRoot, ...entry)),
    ],
    { cwd: join(args.sourceRoot, 'packages', 'harness'), stdout: 'pipe', stderr: 'pipe' },
  )

  const code = await emitted.exited
  if (code !== 0) {
    throw new Error(
      `tsc emitted no declarations (${code}): ${await new Response(emitted.stdout).text()}`,
    )
  }

  await resolveCoreImports(args.declarationRoot)
}

export async function writePluginTypes(args: {
  sourceRoot: string
  directory: string
}): Promise<string> {
  const declarationRoot = join(args.directory, PLUGIN_TYPES_DIRECTORY_NAME)
  await emitPluginDeclarations({ sourceRoot: args.sourceRoot, declarationRoot })

  const outFile = join(args.directory, PLUGIN_TYPES_FILE_NAME)
  await Bun.write(outFile, renderPluginTypes({ declarationRoot }))
  return outFile
}

export const workspaceRootOfThisScript = (): string =>
  join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')

if (import.meta.main) {
  const written = await writePluginTypes({
    sourceRoot: workspaceRootOfThisScript(),
    directory: atlasDirectory(),
  })

  console.log(`plugin types → ${written}`)
}
