#!/usr/bin/env bun
import { existsSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const harnessRoot = join(dirname(fileURLToPath(import.meta.url)), '..')
const pluginsDir = join(harnessRoot, 'src', 'plugins')
const outFile = join(pluginsDir, 'manifest.generated.ts')

const localNameFor = (directory: string): string =>
  directory
    .split(/[-_]/)
    .map((part) => `${(part[0] ?? '').toUpperCase()}${part.slice(1)}`)
    .join('')

async function nativePluginDirectories(): Promise<string[]> {
  if (!existsSync(pluginsDir)) return []

  const found: string[] = []
  for await (const entry of new Bun.Glob('*/index.ts').scan({ cwd: pluginsDir })) {
    const directory = dirname(entry)
    if (directory === '__tests__') continue
    found.push(directory)
  }
  return found.sort()
}

const directories = await nativePluginDirectories()

const body = [
  '// GENERATED by packages/harness/scripts/generate-plugins.ts — do not edit.',
  '',
  "import type { DependencyContainer } from '../container/injection'",
  '',
  ...directories.map(
    (directory) =>
      `import { registerPlugin as register${localNameFor(directory)} } from './${directory}'`,
  ),
  '',
  `export const NATIVE_PLUGIN_IDS: readonly string[] = [${directories
    .map((directory) => `'${directory}'`)
    .join(', ')}]`,
  '',
  'export function registerNativePlugins({ container }: { container: DependencyContainer }): void {',
  ...directories.map((directory) => `  register${localNameFor(directory)}({ container })`),
  '}',
  '',
].join('\n')

await Bun.write(outFile, body)

console.log(`plugins → ${relative(harnessRoot, outFile)} (${directories.length} plugins)`)
