// GENERATED by apps/tui/scripts/generate-plugins.ts — do not edit.

import type { DependencyContainer } from '@dltech/atlas-harness'

import { registerPlugin as registerForeignCheckout } from './foreign-checkout'
import { registerPlugin as registerGithub } from './github'

export const NATIVE_PLUGIN_IDS: readonly string[] = ['foreign-checkout', 'github']

export function registerNativePlugins({ container }: { container: DependencyContainer }): void {
  registerForeignCheckout({ container })
  registerGithub({ container })
}
