import { primitives } from "./primitives";
import { semantic, EColorScheme, type SemanticTheme } from "./semantic";

const GENERATED_HEADER =
  "/* GENERATED by tools/generate-css.ts from src/tokens — edit the tokens, not this file */";

function toKebab(name: string): string {
  return name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function renderVars(vars: Record<string, string>): string[] {
  return Object.entries(vars).map(
    ([name, value]) => `  --${toKebab(name)}: ${value};`,
  );
}

function renderSchemeBlock(selector: string, theme: SemanticTheme): string {
  return [`${selector} {`, ...renderVars(theme), "}"].join("\n");
}

export function buildThemeCss(): string {
  const staticVars: Record<string, string> = {};
  for (const [name, value] of Object.entries(primitives.radius)) {
    staticVars[`radius-${name}`] = value;
  }
  for (const [name, value] of Object.entries(primitives.font)) {
    staticVars[`font-${name}`] = value;
  }

  const themeMappings: string[] = [];
  for (const name of Object.keys(semantic[EColorScheme.Light])) {
    const kebab = toKebab(name);
    themeMappings.push(`  --color-${kebab}: var(--${kebab});`);
  }
  for (const name of Object.keys(staticVars)) {
    themeMappings.push(`  --${name}: var(--${name});`);
  }

  return [
    GENERATED_HEADER,
    "",
    '@import "tailwindcss";',
    "",
    renderSchemeBlock(":root", {
      ...semantic[EColorScheme.Light],
      ...staticVars,
    }),
    "",
    renderSchemeBlock(".dark", semantic[EColorScheme.Dark]),
    "",
    ["@theme inline {", ...themeMappings, "}"].join("\n"),
    "",
  ].join("\n");
}
