import { primitives } from "./primitives";
import { control, layout, radius, row, spaceBase } from "./scale";
import { font, text, tracking, weight } from "./typography";
import { duration, ease, keyframes } from "./motion";
import { EColorScheme, semantic, type SemanticTheme } from "./semantic";

const GENERATED_HEADER =
  "/* GENERATED by tools/generate-css.ts from src/tokens — edit the tokens, not this file */";

const LIGHT_SELECTOR = '[data-theme="day"], [data-theme="light"], .light';

function toKebab(name: string): string {
  return name.replace(/[A-Z]/g, (letter) => `-${letter.toLowerCase()}`);
}

function block(selector: string, lines: string[]): string {
  return [`${selector} {`, ...lines.map((line) => `  ${line}`), "}"].join("\n");
}

function primitiveColorLines(): string[] {
  const lines: string[] = [];
  const { warm, clay, blue, steel, red, amber, green, violet, accentChoices } =
    primitives.color;
  const ramps: Record<string, Record<string, string>> = {
    warm,
    clay,
    blue,
    steel,
    red,
    amber,
    green,
    violet,
  };
  for (const [ramp, steps] of Object.entries(ramps)) {
    for (const [step, value] of Object.entries(steps)) {
      lines.push(`--color-${ramp}-${step}: ${value};`);
    }
  }
  for (const [name, value] of Object.entries(accentChoices)) {
    lines.push(`--color-accent-${name}: ${value};`);
  }
  return lines;
}

function renderThemeBlock(): string {
  const lines: string[] = [];
  lines.push(`--spacing: ${spaceBase};`);
  for (const [name, value] of Object.entries(control)) {
    lines.push(`--spacing-control-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(row)) {
    lines.push(`--spacing-row-${name}: ${value};`);
  }
  lines.push(...primitiveColorLines());
  for (const [name, value] of Object.entries(radius)) {
    lines.push(`--radius-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(font)) {
    lines.push(`--font-${name}: ${value};`);
  }
  for (const [name, step] of Object.entries(text)) {
    lines.push(`--text-${name}: ${step.size};`);
    lines.push(`--text-${name}--line-height: ${step.lineHeight};`);
  }
  for (const [name, value] of Object.entries(weight)) {
    lines.push(`--font-weight-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(tracking)) {
    lines.push(`--tracking-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(ease)) {
    lines.push(`--ease-${name}: ${value};`);
  }
  return block("@theme", lines);
}

function semanticVarName(name: string): string {
  const kebab = toKebab(name);
  if (kebab.startsWith("shadow-") || kebab.startsWith("glow-"))
    return `--${kebab}`;
  return `--${kebab}`;
}

function renderRootBlock(): string {
  const lines: string[] = [];
  for (const [name, value] of Object.entries(semantic[EColorScheme.Dark])) {
    lines.push(`${semanticVarName(name)}: ${value};`);
  }
  for (const [name, value] of Object.entries(duration)) {
    lines.push(`--duration-${toKebab(name)}: ${value};`);
  }
  for (const [name, value] of Object.entries(layout)) {
    lines.push(`--${toKebab(name)}: ${value};`);
  }
  return block(":root", lines);
}

function renderLightBlock(): string {
  const lines: string[] = [];
  for (const [name, value] of Object.entries(semantic[EColorScheme.Light])) {
    lines.push(`${semanticVarName(name)}: ${value};`);
  }
  return block(LIGHT_SELECTOR, lines);
}

function renderInlineThemeBlock(): string {
  const lines: string[] = [];
  for (const name of Object.keys(semantic[EColorScheme.Dark])) {
    const kebab = toKebab(name);
    if (kebab.startsWith("shadow-") || kebab.startsWith("glow-")) {
      lines.push(
        `--shadow-${kebab.replace(/^shadow-/, "").replace(/^glow-/, "glow-")}: var(--${kebab});`,
      );
    } else {
      lines.push(`--color-${kebab}: var(--${kebab});`);
    }
  }
  return block("@theme inline", lines);
}

function renderKeyframes(): string[] {
  return Object.entries(keyframes).map(([name, frames]) =>
    [
      `@keyframes ${name} {`,
      ...Object.entries(frames).map(
        ([stop, rules]) => `  ${stop} { ${rules} }`,
      ),
      "}",
    ].join("\n"),
  );
}

function renderReducedMotion(): string {
  const zeroed = Object.keys(duration)
    .filter((name) => name !== "spinnerFrame")
    .map((name) => `--duration-${toKebab(name)}: 0ms;`);
  return [
    "@media (prefers-reduced-motion: reduce) {",
    block(":root", zeroed),
    "}",
  ].join("\n");
}

export function buildThemeCss(): string {
  return [
    GENERATED_HEADER,
    "",
    '@import "tailwindcss";',
    "",
    renderThemeBlock(),
    "",
    renderRootBlock(),
    "",
    renderLightBlock(),
    "",
    renderInlineThemeBlock(),
    "",
    ...renderKeyframes(),
    "",
    renderReducedMotion(),
    "",
  ].join("\n");
}
