alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: api.byatlas.io
  type: PRIMARY
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: atlas-apps-api
    match:
      authority:
        exact: ""
      path:
        prefix: /
jobs:
- dockerfile_path: apps/api/Dockerfile
  envs:
  - key: DOTENV_PRIVATE_KEY_API_PRODUCTION
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:6sMXx7X/pb2Oemkp1Ai9dbRt/NTCyC9k:E1Mx6NOVNRXdcctQqhUuasDkvSBKoimtBzhMA8MfgGVzMKn7k8nlpyW2mQGoU/fnPet4VHE/oi+W6dbQgIJjd5gijxS140s44Xb0BNVrBt0=]
  - key: APP_TIER
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: MIGRATE_TIER
    scope: RUN_AND_BUILD_TIME
    value: production
  github:
    branch: main
    repo: dennisofficial/atlas
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  kind: PRE_DEPLOY
  name: migrate
  run_command: npm run db:migrate:deploy
name: atlas
region: nyc
services:
- dockerfile_path: apps/api/Dockerfile
  envs:
  - key: DOTENV_PRIVATE_KEY_API_PRODUCTION
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:6sMXx7X/pb2Oemkp1Ai9dbRt/NTCyC9k:E1Mx6NOVNRXdcctQqhUuasDkvSBKoimtBzhMA8MfgGVzMKn7k8nlpyW2mQGoU/fnPet4VHE/oi+W6dbQgIJjd5gijxS140s44Xb0BNVrBt0=]
  - key: APP_TIER
    scope: RUN_AND_BUILD_TIME
    value: production
  github:
    branch: main
    deploy_on_push: false
    repo: dennisofficial/atlas
  health_check:
    http_path: /v1/health
    initial_delay_seconds: 20
  http_port: 8080
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: atlas-apps-api
