import { toCallId, toRunId } from '@dltech/atlas-core'
import { ETurnStatus, type TurnOutcomeWire } from '@dltech/atlas-wire'

import type { TurnOutcome } from '../loop/turn-outcome'

export {
  bearerSubprotocolOf,
  cancelCompactionParamsSchema,
  compactHistoryParamsSchema,
  compactionReplySchema,
  EWireCompactionAnchor,
  EWireCompactScope,
  summariseHistoryParamsSchema,
  channelSignalSchema,
  CHANNEL_PROTOCOL_VERSION,
  CHANNEL_SUBPROTOCOL,
  chunkWireSchema,
  clientFrameSchema,
  decodeClientFrame,
  decodeServeFrame,
  EClientFrame,
  EClientRequest,
  EFinishReason,
  ERetryReason,
  EServeEnv,
  EServeFrame,
  ETurnStatus,
  encodeFrame,
  activateSessionReplySchema,
  applyWorkspaceArchiveReplySchema,
  prepareWorkspaceArchiveReplySchema,
  confirmWorkspaceCleanupParamsSchema,
  confirmWorkspaceCleanupReplySchema,
  publishedWorkspaceWireSchema,
  restoredWorkspaceWireSchema,
  WORKSPACE_EXPORT_DIRECTORY_NAME,
  WORKSPACE_EXPORT_FILE_PATTERN,
  workspaceManifestWireSchema,
  workspaceTreeWireSchema,
  operatorInputReplySchema,
  operatorInputRequestWireSchema,
  provideOperatorInputParamsSchema,
  renameThreadParamsSchema,
  readEventsParamsSchema,
  readEventsReplySchema,
  listContextFilesParamsSchema,
  listContextFilesReplySchema,
  readContextFileParamsSchema,
  readContextFileReplySchema,
  contextFileContentWireSchema,
  readMemoryArchiveReplySchema,
  readSessionArchiveReplySchema,
  readThreadParamsSchema,
  readThreadReplySchema,
  readThreadsReplySchema,
  readTranscriptIdentityParamsSchema,
  restoreTranscriptParamsSchema,
  readTurnsParamsSchema,
  readTurnsReplySchema,
  transcriptIdentityReplySchema,
  rewindApplyParamsSchema,
  rewindCutWireSchema,
  rewindKillWireSchema,
  serveFrameSchema,
  setThreadModelParamsSchema,
  takeBackPendingParamsSchema,
  takeBackPendingReplySchema,
  SERVE_BINARY_PATH,
  SERVE_HOME,
  SERVE_LOCK_PATH,
  SERVE_LOG_PATH,
  SERVE_TOKEN_PATH,
  SERVE_VERSION_PATH,
  threadModelWireSchema,
  toSendId,
  tokenFromSubprotocols,
  turnOutcomeWireSchema,
  wireEventSchema,
  wireThreadSchema,
  wireTurnSchema,
} from '@dltech/atlas-wire'

export type {
  ActivateSessionReply,
  CancelCompactionParams,
  CompactHistoryParams,
  CompactionReply,
  SummariseHistoryParams,
  ApplyWorkspaceArchiveReply,
  ClientFrame,
  OperatorInputReply,
  OperatorInputRequestWire,
  ContextFileContentWire,
  ListContextFilesParams,
  PrepareWorkspaceArchiveReply,
  ConfirmWorkspaceCleanupReply,
  ProvideOperatorInputParams,
  ReadContextFileParams,
  RestoredWorkspaceWire,
  WorkspaceManifestWire,
  PublishedWorkspaceWire,
  ReadEventsParams,
  ReadThreadParams,
  ReadTranscriptIdentityParams,
  ReadTurnsParams,
  RenameThreadParams,
  RestoreTranscriptParams,
  RewindApplyParams,
  RewindCutWire,
  RewindKillWire,
  SaidImageWire,
  ServeFrame,
  SetThreadModelParams,
  TakeBackPendingParams,
  TakeBackPendingReply,
  TurnOutcomeWire,
  WireDraft,
  WireEvent,
  WireThread,
  WireTurn,
} from '@dltech/atlas-wire'

export const turnOutcomeFromWire = (outcome: TurnOutcomeWire): TurnOutcome => {
  if (outcome.status === ETurnStatus.Paused) {
    return { ...outcome, runId: toRunId(outcome.runId), callId: toCallId(outcome.callId) }
  }
  if (outcome.status === ETurnStatus.Failed) {
    return { ...outcome, runId: toRunId(outcome.runId), cause: undefined }
  }
  return { ...outcome, runId: toRunId(outcome.runId) }
}
