// GENERATED by packages/harness/scripts/generate-skills.ts — do not edit.

import { embeddedFile, type EmbeddedSkillFile } from "../embedded-bundle"

export const FILES: readonly EmbeddedSkillFile[] = [
  embeddedFile({ path: "references/assembly.md", digest: "aa9b4a5e6ce3b0a991c8d623ae0870e4d9681d922d62d5c81261748106a0997b", load: () => import("../../../skills/video/references/assembly.md" as string, { with: { type: 'file' } }) }),
  embeddedFile({ path: "references/hyperframes.md", digest: "c83985570d95d667cbf8f593b645b754479f56a4e65323f09d2ddd25b2fbb030", load: () => import("../../../skills/video/references/hyperframes.md" as string, { with: { type: 'file' } }) }),
  embeddedFile({ path: "references/remotion.md", digest: "a3e8a6f9d1fdd9e68f750e631312826c3d5f6e06df4a87d9ac99eda351819897", load: () => import("../../../skills/video/references/remotion.md" as string, { with: { type: 'file' } }) }),
  embeddedFile({ path: "references/terminal.md", digest: "4490ae6dc8a13a46bd8e0b96ad40ddcde0317bf677590fb55e6cd146be6399fc", load: () => import("../../../skills/video/references/terminal.md" as string, { with: { type: 'file' } }) }),
  embeddedFile({ path: "references/workflow.md", digest: "28df58b8971bc24f8f0ed5401fde9578f95c2b0c296871b621e7b341e09d6a2b", load: () => import("../../../skills/video/references/workflow.md" as string, { with: { type: 'file' } }) }),
]
