// GENERATED by apps/tui/scripts/generate-skills.ts — do not edit.

export const BUILT_IN_SKILLS: readonly { path: string; text: string }[] = [
  {
    path: 'commit/SKILL.md',
    text: `---
name: commit
description: Stage the current work and write a conventional commit message for it.
argument-hint: [scope]
---

Review the staged and unstaged changes with \`git status\` and \`git diff\`, then commit them.

Write the message as \`<type>(<scope>): <description>\` — an imperative, lowercase description
under seventy-two characters. Pick the type from \`feat\`, \`fix\`, \`refactor\`, \`docs\`, \`test\`,
\`chore\`. The merged PR title is the release decision — \`feat\` cuts a minor, \`fix\` a patch — so
\`feat\` means a user can do something they couldn't before; tweaks, restyles, and polish are
\`fix\` or \`refactor\`. Add a body only when the change needs a reason that the diff cannot carry.

Never add attribution trailers. Never pass \`--no-verify\`. If the changes span more than one
concern, split them into separate commits rather than writing one message that hedges.
`,
  },
  {
    path: 'resolving-merge-conflicts/SKILL.md',
    text: `---
name: resolving-merge-conflicts
description: Use when you need to resolve an in-progress git merge/rebase conflict.
---

1. **See the current state** of the merge/rebase. Check git history, and the conflicting files.

2. **Find the primary sources** for each conflict. Understand deeply why each change was made, and what the original intent was. Read the commit messages, check the PRs, check original issues/tickets.

3. **Resolve each hunk.** Preserve both intents where possible. Where incompatible, pick the one matching the merge's stated goal and note the trade-off. Do **not** invent new behaviour. Always resolve; never \`--abort\`.

4. Discover the project's **automated checks** and run them — typically typecheck, then tests, then format. Fix anything the merge broke.

5. **Finish the merge/rebase.** Stage everything and commit. If rebasing, continue the rebase process until all commits are rebased.
`,
  },
]
